#pragma once

#include <windows.h>

//
// Message define
//
inline UINT WM_SHOW_MAIN_WINDOW;
inline UINT WM_HIDE_MAIN_WINDOW;
inline UINT WM_MOVE_CANDIDATE_WINDOW;
inline const UINT WM_CLS_DICT_CACHE = WM_USER + 100;
inline const UINT WM_DELETE_CANDIDATE = WM_USER + 101;
inline const UINT WM_LANGBAR_RIGHTCLICK = WM_USER + 102;
inline const UINT WM_IMEACTIVATE = WM_USER + 103;
inline const UINT WM_IMEDEACTIVATE = WM_USER + 104;
inline const UINT WM_IMESWITCH = WM_USER + 105;
inline const UINT WM_PUNCSWITCH = WM_USER + 106;
inline const UINT WM_DOUBLESINGLEBYTESWITCH = WM_USER + 107;
inline const UINT UPDATE_FTB_STATUS = WM_USER + 108;
