#!/usr/bin/env python3
"""Generate MetasequoiaImeEngine/quanpin/autocorrect_table.h from quanpin_utils.cpp.

The intact pinyin list is parsed directly from the engine source, so the
generated table can never drift from the runtime syllable list.

Usage:
    python scripts/generate_quanpin_autocorrect.py          # regenerate the header
    python scripts/generate_quanpin_autocorrect.py --check  # verify the header is up to date (CI)
"""

from __future__ import annotations

import pathlib
import re
import sys

ENGINE_DIR = pathlib.Path(__file__).resolve().parents[2] / "vendor" / "MetasequoiaImeEngine"
UTILS_PATH = ENGINE_DIR / "quanpin" / "quanpin_utils.cpp"
OUT_PATH = ENGINE_DIR / "quanpin" / "autocorrect_table.h"

# QWERTY letter-key neighbors (finger-movement range, letter keys only).
QWERTY_NEIGHBORS = {
    "q": ["w", "a"],
    "w": ["q", "e", "s", "a"],
    "e": ["w", "r", "s", "d"],
    "r": ["e", "t", "d", "f"],
    "t": ["r", "y", "f", "g"],
    "y": ["t", "u", "g", "h"],
    "u": ["y", "i", "h", "j"],
    "i": ["u", "o", "j", "k"],
    "o": ["i", "p", "k", "l"],
    "p": ["o", "l"],
    "a": ["q", "w", "s", "z"],
    "s": ["a", "w", "d", "e", "x", "z"],
    "d": ["s", "e", "r", "f", "c", "x"],
    "f": ["d", "r", "t", "g", "v", "c"],
    "g": ["f", "t", "y", "h", "b", "v"],
    "h": ["g", "y", "u", "j", "n", "b"],
    "j": ["h", "u", "i", "k", "m", "n"],
    "k": ["j", "i", "o", "l", "m"],
    "l": ["k", "o", "p"],
    "z": ["a", "s", "x"],
    "x": ["z", "s", "d", "c"],
    "c": ["x", "d", "f", "v"],
    "v": ["c", "f", "g", "b"],
    "b": ["v", "g", "h", "n"],
    "n": ["b", "h", "j", "m"],
    "m": ["n", "j", "k"],
}

HEADER_TEMPLATE = """\
// Generated by scripts/generate_quanpin_autocorrect.py -- DO NOT EDIT.
// Quanpin typing autocorrection table: wrong spelling -> correct syllable.
// Rules: single adjacent-letter transposition, or single neighbor-key
// substitution on a QWERTY layout, applied to one legal syllable.
// Every key is a non-legal pinyin string and maps to exactly one syllable.
#pragma once

#include <cstddef>

namespace quanpin::autocorrect
{{
struct Entry
{{
    const char *wrong;
    const char *correct;
}};

inline constexpr Entry kEntries[] = {{
{entries}
}};

inline constexpr std::size_t kEntryCount = sizeof(kEntries) / sizeof(kEntries[0]);

}} // namespace quanpin::autocorrect
"""


def extract_intact_pinyin_list() -> list[str]:
    text = UTILS_PATH.read_text(encoding="utf-8")
    match = re.search(r"intact_pinyin_list\(\)[\s\S]*?kList = \{([\s\S]*?)\};", text)
    if not match:
        raise SystemExit("ERROR: cannot find intact_pinyin_list in " + str(UTILS_PATH))
    return re.findall(r'"([a-z]+)"', match.group(1))


def build_entries(syllables: list[str]) -> dict[str, str]:
    valid = set(syllables)
    mapping: dict[str, str] = {}

    def add_variant(variant: str, correct: str) -> None:
        if (
            variant == correct
            or variant in valid
            or len(variant) < 2
            or len(variant) > 6
            or "'" in variant
        ):
            return
        existing = mapping.get(variant)
        if existing is None:
            mapping[variant] = correct
        elif existing != correct:
            # Ambiguous: the same wrong string would map to two syllables.
            # Drop it entirely so the runtime never guesses.
            del mapping[variant]

    for syllable in syllables:
        if len(syllable) < 2:
            continue
        # Adjacent transpositions: sahng -> shang.
        for i in range(len(syllable) - 1):
            variant = syllable[:i] + syllable[i + 1] + syllable[i] + syllable[i + 2 :]
            add_variant(variant, syllable)
        # Neighbor-key substitutions: shabg -> shang (n -> b).
        for i, ch in enumerate(syllable):
            for neighbor in QWERTY_NEIGHBORS.get(ch, ()):
                add_variant(syllable[:i] + neighbor + syllable[i + 1 :], syllable)

    return mapping


def render_header(entries: dict[str, str]) -> str:
    lines = []
    for wrong, correct in sorted(entries.items()):
        lines.append(f'    {{"{wrong}", "{correct}"}},')
    return HEADER_TEMPLATE.format(entries="\n".join(lines))


def main() -> int:
    syllables = extract_intact_pinyin_list()
    if not syllables:
        raise SystemExit("ERROR: extracted empty pinyin list")
    entries = build_entries(syllables)
    rendered = render_header(entries)

    if "--check" in sys.argv[1:]:
        if not OUT_PATH.exists():
            raise SystemExit(f"ERROR: {OUT_PATH} is missing")
        if OUT_PATH.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"ERROR: {OUT_PATH} is stale; rerun generate_quanpin_autocorrect.py")
        print(f"OK: {OUT_PATH} is up to date ({len(entries)} entries)")
        return 0

    OUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUT_PATH} with {len(entries)} entries "
          f"(from {len(syllables)} legal syllables)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())